export const emptyEmailErrorMessage = 'Email should not be empty'
export const invalidEmailErrorMessage = 'Please provide valid email address'
export const emptyPasswordErrorMessage = 'Password should not be empty'
export const emptyAgeErrorMessage = 'Age should not be empty'
export const emptyPriceErrorMessage = 'Price should not be empty'