export enum ActionType {
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_ERROR = "LOGIN_ERROR",
    USER_LOGOUT = "USER_LOGOUT",

    CALCULATE_SUCCESS = "CALCULATE_SUCCESS",
    CALCULATE_ERROR = "CALCULATE_ERROR"
}